######################################################################
# Automatically generated by qmake (2.01a) Fri May 27 14:46:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lmarkdown

QT += webkit


# Input
HEADERS += markdownview.h
SOURCES += main.cpp markdownview.cpp
